name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # ou a versão do Node.js usada no projeto

      # Instalar dependências na subpasta 'client' (ajuste conforme necessário)
      - name: Install dependencies
        run: |
          cd client # Navega até a subpasta onde está o projeto
          npm install # Instala as dependências

      # Executar os testes na subpasta 'client' (ajuste conforme necessário)
      - name: Run tests
        run: |
          cd client # Navega até a subpasta onde estão os testes
          npm test # Executa os testes

      # Publicar resultados no GitHub (opcional)
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: client/test-results/ # Ajuste se o diretório de resultados for diferente
