name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checar o código do repositório
      - name: patas-solidarias
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # ou a versão do Node.js usada no projeto

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Executar os testes
      - name: Run tests
        run: npm test

      # Publicar resultados no GitHub
      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

      
