name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # ou a versão do Node.js usada no projeto

      # Instalar dependências na subpasta 'client' (ajuste conforme necessário)
      - name: Install dependencies
        run: |
          cd client 
          npm install 

      # Executar os testes na subpasta 'client' (ajuste conforme necessário)
      - name: Run tests
        run: |
          cd client 
          npx test
